version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workdaydb
    networks:
      pomodoro-net:

  workday-service:
    container_name: workday-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      pomodoro-net:
    restart: on-failure

networks:
  pomodoro-net: